name: "check"
on:
  pull_request:
    branches:
      - main
      - beta
  workflow_call:
permissions:
  contents: read
concurrency:
  group: check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn typecheck
      - run: yarn test:ci
      - uses: codecov/codecov-action@v6.0.0
        with:
          files: coverage/lcov.info
      - run: yarn build
      - uses: actions/upload-artifact@v4
        if: success() && github.event_name == 'push'
        with:
          name: dist
          path: dist
          retention-days: 1
